apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  labels:
    app: nginx
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
	  - name: nginx-cm
	    configMap:
	      name: nginxconfigmap	  
  containers:
    - name: task-pv-container
      image: nginx-php
	  resources:
        limits:
          memory: 500Mi
        requests:
          memory: 100Mi	  
      ports:
        - containerPort: 80
          name: "http"
      volumeMounts:
        - mountPath: "/opt/nginx/html"
          name: task-pv-storage
        - mountPath: "/mnt/env"
          name: nginx-cm
